version: '3.3'

services:
  redis:
    image: redis:6
    container_name: redis
    restart: always
    command: redis-server --requirepass 1qaz2wsx
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    networks:
      - redis

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=1qaz2wsx
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - $PWD/storage/rabbitmq-node-1:/var/lib/rabbitmq
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

volumes:
  redis:
    driver: local

networks:
  redis:
